site_name: Hell Let Loose Settings Wiki
site_url: https://StertaFed.github.io/hll-settings-wiki/

theme:
  name: kpn
nav:
  - 'Home': 'index.md'
  - 'Windows Basics': 'windows_basics.md'
  - 'Optimised PC settings': 'optimised_pc_settings.md'
  - 'Nvidia Graphics Filters': 'nvidia_graphics_filters.md'
  - 'AMD Graphics Filters': 'amd_graphics_filters.md'
  - 'DWM LUT Alternative Filters': 'dwm_lut_alternative_filters.md'
  - 'Optimal Game Settings': 'optimal_game_settings.md'

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji
plugins:
  - glightbox
  - mkdocs-video
extra_css:
  - stylesheets/extra.css
