site_name: Hell Let Loose Settings Wiki
theme:
  name: material
nav:
  - 'Home': 'index.md'
  - 'Optimal Game Settings': 'optimal_game_settings.md'
  - 'Nvidia Graphics Filters': 'nvidia_graphics_filters.md'
  - 'Windows Basics': 'windows_basics.md'
  - 'Optimised PC settings': 'optimised_pc_settings.md'
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
plugins:
  - glightbox
extra_css:
  - stylesheets/extra.css